name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  VERSION: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/raspberryprogramming/tc2-bbs-mesh:$VERSION
    - name: Add latest tag to docker image
      run: docker tag ghcr.io/raspberryprogramming/tc2-bbs-mesh:$VERSION ghcr.io/raspberryprogramming/tc2-bbs-mesh:latest
    - name: Push docker image to ghcr
      run: docker push ghcr.io/raspberryprogramming/tc2-bbs-mesh:$VERSION
    - name: Push docker latest image to ghcr
      run: docker push ghcr.io/raspberryprogramming/tc2-bbs-mesh:latest
